//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Resource", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actions.
        /// </summary>
        internal static string Actions {
            get {
                return ResourceManager.GetString("Actions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back to List.
        /// </summary>
        internal static string BackToList {
            get {
                return ResourceManager.GetString("BackToList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Car Number.
        /// </summary>
        internal static string CarNumber {
            get {
                return ResourceManager.GetString("CarNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this fine?.
        /// </summary>
        internal static string ConfirmDelete {
            get {
                return ResourceManager.GetString("ConfirmDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        internal static string Create {
            get {
                return ResourceManager.GetString("Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Fine.
        /// </summary>
        internal static string CreateFine {
            get {
                return ResourceManager.GetString("CreateFine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fine was successfully created..
        /// </summary>
        internal static string CreateSuccessMessage {
            get {
                return ResourceManager.GetString("CreateSuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        internal static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kustuta.
        /// </summary>
        internal static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Fine.
        /// </summary>
        internal static string DeleteFine {
            get {
                return ResourceManager.GetString("DeleteFine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fine was successfully deleted..
        /// </summary>
        internal static string DeleteSuccessMessage {
            get {
                return ResourceManager.GetString("DeleteSuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        internal static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Fine.
        /// </summary>
        internal static string EditFine {
            get {
                return ResourceManager.GetString("EditFine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fine was successfully updated..
        /// </summary>
        internal static string EditSuccessMessage {
            get {
                return ResourceManager.GetString("EditSuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export to Excel.
        /// </summary>
        internal static string ExportToExcel {
            get {
                return ResourceManager.GetString("ExportToExcel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fine Information.
        /// </summary>
        internal static string FineInformation {
            get {
                return ResourceManager.GetString("FineInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fine List.
        /// </summary>
        internal static string FineList {
            get {
                return ResourceManager.GetString("FineList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fine Overview.
        /// </summary>
        internal static string FineOverview {
            get {
                return ResourceManager.GetString("FineOverview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find fines.
        /// </summary>
        internal static string Fines {
            get {
                return ResourceManager.GetString("Fines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        internal static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log In.
        /// </summary>
        internal static string LogIn {
            get {
                return ResourceManager.GetString("LogIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log Off.
        /// </summary>
        internal static string LogOff {
            get {
                return ResourceManager.GetString("LogOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No fines found..
        /// </summary>
        internal static string NoFinesFound {
            get {
                return ResourceManager.GetString("NoFinesFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pay Fine.
        /// </summary>
        internal static string PayFine {
            get {
                return ResourceManager.GetString("PayFine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        internal static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search by Car Number.
        /// </summary>
        internal static string SearchCarNumber {
            get {
                return ResourceManager.GetString("SearchCarNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount.
        /// </summary>
        internal static string Sum {
            get {
                return ResourceManager.GetString("Sum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Email.
        /// </summary>
        internal static string UserEmail {
            get {
                return ResourceManager.GetString("UserEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speed.
        /// </summary>
        internal static string Velocity {
            get {
                return ResourceManager.GetString("Velocity", resourceCulture);
            }
        }
    }
}
